### ISSUE TITLE
Web Server: failed job [Fatal error: Exit code 1 ()]

### ISSUE THREAD

**Issue by saihivarkar** [thh32/Protologger#4]
Hi! First of all, thank you for developing an amazing tool for budding taxonomists.
Recently, I have uploaded a genome and 16S fasts file of one of my novel strain. It took almost three days for the files to process. Then today when I ran the Protologger, it returned with the "Fatal error: Exit code 1 ()" job message. So, I want to know the reason for my job failure.
Thank you in advance!

Some details I think you would require:
History Content API ID: 88b0d7c2322f1085
Job API ID: 4e77bbc3b46ddd17
History API ID: dea5f1d7ed1cb218
UUID: ea5ec2b9-6e26-4a05-abdd-5a1e4d88acfa

**Comment by thh32** [comment]
Oh no! I'm sorry to hear that. I know long wait times are currently an issue, unfortunately due to the large amount of RAM needed for the analysis I have had to limit it to 3 concurrent jobs at a time and there have been ~20 in the queue consistently recently. Would you mind sending your submission files to the admin address on the website and I can try running it locally to see what the issue was. I will also delve into the job history now as well. 

Thank you for reporting this issue.

**Comment by thh32** [comment]
Is the isolate you submitted an Archaea? From the looks at the output GTDB-Tk didn't produce a bac120 output file, coupled with CheckM providing the following output;
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Bin Id              Marker lineage       # genomes   # markers   # marker sets   0    1    2   3   4   5+   Completeness   Contamination   Strain heterogeneity  
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
  dataset_3992   p__Euryarchaeota (UID4)       45         299           202        1   297   1   0   0   0       99.50            0.50               0.00          
-------------------------------------------------------------------------------------------------------------------------------------------------------------------


Unfortunately Protologger only works with Bacteria currently, but we will be implementing it for Archaea soon!

**Comment by saihivarkar** [comment]
Hi Thomas!
The isolate I submitted is a Bacteria. The bacteria's genome is 119 contigs, and its 16S sequence is around 1050 base pairs. Is it because of the quality of the genome and 16S sequence that the job is failing?

**Comment by thh32** [comment]
Ok so I managed to obtain the genome file from the server and to see if our GTDB-Tk implementation was wrong, submitted the genome to MiGA (http://microbial-genomes.org/) which identified the genome as;

```
root (p-value 0****)
domain Archaea (p-value 0****)
phylum Euryarchaeota (p-value 6.33e-05****)
class Thermococci (p-value 9.49e-05****)
order Thermococcales (p-value 0.000728****)
family Thermococcaceae (p-value 0.0056****)
genus Thermococcus (p-value 0.186*)
species Thermococcus litoralis (p-value 0.724)
subspecies (p-value 0.913)
dataset Thermococcus litoralis DSM 5473 (p-value 0.923)
```

Furthermore, the closest relatives were identified to be;

```The closest relatives found by MiGA in the database were Thermococcus litoralis DSM 5473 NC 022084T (79.71% AAI) and Thermococcus sibiricus MM 739 NC 012883T (66.3% AAI).```


To double check this I submitted the genome to TYGS, which also identified the closest relative as Thermococcus litoralis.

Based on these findings, I would suggest your isolate is a close relative of Thermococcus, making it an Archaea and therefore unable to be analysed using Protologger in its current form.

Incase I obtained the wrong genome, I would suggest you submit your genome to both of these alternative tools to ensure it is Bacterial as you stated in your last message. If so, please email me the sequence files so I can delve deeper into this as it would then represent an issue with Protologgers ability to study Bacteria.

**Comment by saihivarkar** [comment]
Thank you Thomas for your efforts. It was a mere blunder in naming the files in my shared folder in Dropbox. I too had checked the 16S sequence via blastn after you raised the query of Archaea.
I am deeply sorry to put u in this situation due to my mistake. Protologger is absolutely working fine in sweetly ignoring Archaea, however, I am eagerly waiting for it to start accepting Archaea!
Best wishes for Protologger 2.0!

**Comment by thh32** [comment]
Glad to have this confirmed and no worries, hopefully we can get Archaea working soon!
