### ISSUE TITLE
Suggestion for a new KEGG grouping

### ISSUE THREAD

**Issue by Anto007** [thh32/Protologger#5]
Hi,

Nice tool but I'll wait for the full conda version to start using it more extensively [not enough patience to use it over Galaxy;-)]. May I suggest the addition of a new KEGG grouping "Methane/C1 metabolism" for methylotrophic bacteria? Methylotrophic bacteria that are capable of growing on C1 compounds (e.g., methane, methanol) as their sole carbon and energy sources can have the prefix 'Methyl' added to their taxon names.

**Comment by thh32** [comment]
Hey,

Yeah I totally understand not wanting to queue for access, hopefully you wont have to wait too long for the conda version!

Regarding the inclusion of methane utilisation, is there a specific KEGG module you would wish to be included? From looking at the modules methane is assigned to, I would assume "Methane oxidation, methanotroph, methane => formaldehyde
" would be best suited? Thanks for the suggestion as well for names, this is exactly what we are after from the community so are very grateful for your input!

**Comment by Anto007** [comment]
Thank you for your response. Yes, the KEGG module "Methane oxidation, methanotroph, methane => formaldehyde" would be suitable for the specific case I mentioned. Btw, I had submitted this Job 811210de8067609a (UUID: | 6c8b8b4d-9cc6-4c60-a6d7-9455728cd758) on Galaxy last Sunday and I'm yet to see any results. I suppose my job will start running when resources become available?

**Comment by thh32** [comment]
Perfect, then I will start including that module into the pathway analysis.

Unfortunately our server is seeing extremely high use at the moment as some users submitted ~50 jobs each but yes your job will start running once resources are available. Hopefully that is soon and we are looking into options to expand our resources but currently we are limited to running 3 jobs at a time.

**Comment by thh32** [comment]
The additional module has now been included within Protologger if you wish to rerun your analysis.

I have noticed that our queue on the web-server is now reduced so I hope you job finally finished! My apologies for the long wait and if you have any further suggestions for additional pathways, let me know!

**Comment by Anto007** [comment]
Thank you. The main analysis result files have become available but when I tried to run GAN on Galaxy, I got the below error message: 

WARNING: You are using pip version 20.1; however, version 21.1.2 is available.
You should consider upgrading via the '/DATA/galaxy-run/galaxy/.venv/bin/python3 -m pip install --upgrade pip' command.
WARNING: You are using pip version 20.1; however, version 21.1.2 is available.
You should consider upgrading via the '/DATA/galaxy-run/galaxy/.venv/bin/python3 -m pip install --upgrade pip' command.
WARNING: You are using pip version 20.1; however, version 21.1.2 is available.
You should consider upgrading via the '/DATA/galaxy-run/galaxy/.venv/bin/python3 -m pip install --upgrade pip' command.
          ----- G A N  -----        
   the great automatic nomenclator  

Input files loaded
 - 10% combinations generated...
 - 20% combinations generated...
 - 30% combinations generated...
 - 40% combinations generated...
 - 50% combinations generated...
 - 60% combinations generated...
 - 70% combinations generated...
 - 80% combinations generated...
Traceback (most recent call last):
  File "/DATA/galaxy-run/galaxy/tools/protonamer/bin/gan-master/scripts/gan-genus.py", line 326, in <module>
    combinedEtym, fullEtym, rawEtym = combine_etymology(triplet, [prefixes, mids])
  File "/DATA/galaxy-run/galaxy/tools/protonamer/bin/gan-master/scripts/gan-genus.py", line 203, in combine_etymology
    if not pd.isna(w[part][key]):
  File "/DATA/galaxy-run/galaxy/.venv/lib/python3.6/site-packages/pandas/core/generic.py", line 1330, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "/DATA/galaxy-run/galaxy/tools/protonamer/ProtoName-v0.1.py", line 347, in <module>
    for line in open( dir_path +'Input/' + project_name + '/gan.html'):
IOError: [Errno 2] No such file or directory: '/DATA/galaxy-run/galaxy/tools/protonamer/Input/kmhfevxd/gan.html'

**Comment by Anto007** [comment]
Also, nice Spider plot but I noticed a minor typo on it- "Prevalence"

**Comment by thh32** [comment]
Hmm that is very strange about the GAN, I saw a job failed and ran a test dataset through and it worked fine, would you mind emailing me your Protologger overview file for me to identify the issue with?

Also thanks for spotting the spelling mistake for the spider plot and  Im glad you like it (corrected the spelling now).

**Comment by Anto007** [comment]
Emailed you now the file; thanks!

**Comment by thh32** [comment]
So I have found the issue, firstly 'oral' was searched for before 'coral' so your microbe was assigned to the wrong environment (resolved) and secondly the oral file had a duplicate entry from the combination of multiple lists, which has also been resolved.

Hopefully the GAN-extension should now work for you! Please let me know if it does.

Thanks,
Tom

**Comment by Anto007** [comment]
Many thanks Tom; I can confirm that the rerun has worked.

**Comment by thh32** [comment]
Thanks for the confirmation!
