### ISSUE TITLE
More stringent cutoff possible for habitat distribution search?

### ISSUE THREAD

**Issue by Anto007** [thh32/Protologger#6]
I was wondering if users could opt for a more stringent cutoff at 99% while searching against amplicon libraries available on the IMNGS database? Also, I think that there are >300,000 libraries available on the IMNGS database but only a subset of it appears to be used for searching on Protologger?

**Comment by thh32** [comment]
Hi Antony,

We have opted for minimal customisation of Protologger to ensure consistency between protologues, but we will definitely consider making the cut-off stricter in the next iteration.

Yes there are many additional samples in IMNGS (soon to be 1 million in the next big release!), but searching all of those, along with the rest of the analysis Protologger provides, would be too computationally intensive, and infringe on the purpose of IMNGS itself. This is why we were able to include reduced datasets for a select number of environments for which a sufficient number of samples exist.

In the next iteration we hope to include a few additional samples, but the major focus, ecologically, will be on bulking the MAG database, which I hope to both expand the coverage for the current environments, as well as include ~50 additional environments, if possible.
