### ISSUE TITLE
Suggestion for a denitrification KEGG grouping

### ISSUE THREAD

**Issue by Anto007** [thh32/Protologger#7]
May I suggest the addition of a new KEGG grouping "Denitrification, nitrate => nitrogen" (as in here- https://www.genome.jp/kegg-bin/show_module?M00529) ? Bacteria that are capable of denitrification can have genus names such as 'Nitratireductor' or species names such as 'denitrificans', 'nitrativorans', 'nitratireducenticrescens'

**Comment by thh32** [comment]
Hi Antony,

I have now included this pathway and included four additional species names associated with it ('nitratireducens' as well as the three you mention).

Thanks,
Tom
